### PR TITLE
Add Resources

### PR DESCRIPTION
**Pull request by psmit03**
- Allows resources to be added
- Removes notes section
- Adds overflow for add-question-sheet on explore page

https://github.com/MewingCentral/FEPrep/assets/112008647/1508083c-3f7b-4b7a-bb5d-4af6c211d953

### CODE REVIEW

**Review by DanyPalma — APPROVED** [review]
somebody cooked here. We should see if we need to either 

1) implement a restriction on who can upload resources
2) have some sort of moderation?

**Comment by DanyPalma** [comment]
fix formatting plox

**Comment by psmit03** [comment]
the add resource button only shows up for users of type "Teacher" @DanyPalma 
image

**Comment by DanyPalma** [comment]
sounds good. We might want to consider converting the api to a protected procedure then

**Comment by DanyPalma** [comment]
GO GO GO GO GO GO

image

**Comment by DanyPalma** [comment]
@goonbotbanana

**Pull request merged**
