### PR TITLE
update primary color variable lightness property

### PR DESCRIPTION
**Pull request by psmit03**
OLD:
Screenshot 2024-03-05 at 12 36 08 AM
NEW:
Screenshot 2024-03-05 at 12 35 50 AM
- This raises the lightness property for the primary variable in the global css file for the nextjs app **specifically for light mode.** The default primary color for dark mode from the shadcn theme has not been edited.

### CODE REVIEW

**Comment by LightBounded** [comment]
ngl, not a current fan of the current colors we have so far

**Comment by LightBounded** [comment]
https://ui.shadcn.com/themes

You think we should opt to use the default blue theme that's here on shadcn?

**Comment by psmit03** [comment]
image

**Review by qnbby — APPROVED** [review]
yeah this is the best thing for any FE prepper good good :3

**Pull request merged**
