### PR TITLE
Expanded page, added button to clear all filters

### PR DESCRIPTION
**Pull request by LuisMInfante**
Screen Shot 2024-04-09 at 6 21 12 PM

Instead of having to individually click every dropdown to clear filters individually, it can now be done all at once :)

**The original functionality is still intact**, in case a user wants to just clear an individual column.

### CODE REVIEW

**Review by psmit03 — APPROVED** [review]
image

**Comment by DanyPalma** [comment]
who approved this? i need ot have a word with you

**Comment by DanyPalma** [comment]
@goonbotbanana in my office now

**Comment by DanyPalma** [comment]
image

**Pull request merged**
